backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/image"
public_folder: "/image"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "posts"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - { label: "Tags", name: "tags", widget: "string", required: true }
      - {
          label: "Category",
          name: "category",
          widget: "string",
          required: true,
        }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Description",
          name: description,
          widget: text,
          required: true,
        }
